package main

// The text for the user to type.
// Array of paragraphs used for the typing test.
var paragraphs = []string{
	"The quick brown fox jumps over the lazy dog. This classic sentence is often used to test typing skills because it contains every letter of the English alphabet. Practicing regularly can significantly improve your typing speed and accuracy, which are valuable assets in many professional and academic settings. Remember to maintain good posture and keep your fingers close to the home row keys for optimal efficiency. It is truly remarkable how much progress can be made with consistent effort and dedicated practice sessions.",
	"Sunlight streamed through the ancient oak trees, dappling the forest floor with patterns of light and shadow. A gentle breeze rustled the leaves, creating a soft, whispering sound that echoed through the quiet woods. Squirrels chattered excitedly as they scurried up rough bark, their bushy tails twitching. The air was filled with the earthy scent of damp soil and decaying leaves, a perfume unique to this tranquil haven. Exploring such natural beauty often provides a welcome escape from the hustle and bustle of everyday life, offering a chance to reconnect with the serene rhythm of the natural world.",
	"Undeterred by the inclement weather, the intrepid explorers pressed onward, their resolve unyielding. They navigated treacherous terrain, their progress meticulously documented in their journals. Each discovery, however small, fueled their collective determination and reinforced their belief in the significance of their expedition. The sheer vastness of the unexplored territory presented both daunting challenges and unparalleled opportunities for scientific advancement. Ultimately, their perseverance and meticulous attention to detail would undoubtedly pave the way for future generations of researchers and adventurers.",
	"I need to pick up some groceries on the way home from work today. We're completely out of milk, and I think we also need bread, eggs, and maybe some fruit. I should also check if we have any pasta; it's been a while since we had spaghetti. It's important to plan meals ahead of time to avoid last-minute trips to the store and ensure we're eating balanced diets. Hopefully, the supermarket won't be too crowded this evening, as that can sometimes make the experience a bit more stressful than it needs to be.",
	"The contemplation of abstract concepts can be both intellectually stimulating and emotionally profound. It requires a willingness to engage with ideas that may not have immediate, tangible applications but nonetheless contribute to a deeper understanding of existence. Through philosophical inquiry and critical thinking, we begin to unravel the complexities of the human condition and our place within the grand tapestry of the universe. Embracing uncertainty and questioning established norms are crucial elements in this ongoing journey of discovery and personal growth.",
}

var pythonParagraph = []string{
	"calculate_average(numbers_list). Inside this function, we'll initialize a total_sum = 0 and a count = 0. We can then iterate through each number in numbers_list, adding it to total_sum and incrementing count. If count is greater than zero, we'll return total_sum / count; otherwise, we'll return 0. This basic structure handles potential division by zero errors effectively.",
	"Consider a list of dictionaries, where each dictionary represents a user with keys like 'user_id', 'username', and 'email'. To process this data, we might use a for user_data in users:. Inside the loop, we could access the username using user_data['username'] and then perform some validation or transformation. For instance, we might check if the email address user_data['email'] contains the '@' symbol before proceeding.",
	"When dealing with file input/output, it's crucial to manage resources properly. We can use a with open('config.txt', 'r') as file_handle: block. Within this context, we might read lines using file_handle.readlines(), and then process each line.strip(). If a line starts with '#', it's a comment and should be skipped using continue. Otherwise, we could split the line into key-value pairs using line.split('=', 1) and store them in a dictionary.",
	"To perform network operations, we'll import the requests library: import requests. Then, we can make a GET request to a specific URL, for example, response = requests.get('https://api.example.com/data'). It's good practice to wrap this in a try-except block to handle potential requests.exceptions.RequestException errors. Inside the try block, we check if response.status_code == 200:, and if so, we can access the JSON data with response.json().",
	"Python's concise syntax allows for powerful expressions. A lambda function, such as square = lambda x: x * x, can be used for simple, one-off operations. Similarly, list comprehensions provide an elegant way to create lists. For example, squared_numbers = [x**2 for x in range(1, 11) if x % 2 == 0] will generate a list of the squares of even numbers between 1 and 10. This is often more readable and efficient than traditional for loops for such tasks.",
}
